development:
  adapter: postgresql
  encoding: unicode
  database: tdd_tunr_development
  host: localhost
  pool: 5
  username: dylanoshea
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tdd_tunr_test
  host: localhost
  pool: 5
  username: dylanoshea
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: tdd_tunr_production
  host: localhost
  pool: 5
  username: dylanoshea
  password:
